Create accordion.html.twig
kevinpapst/TablerBundle pull request #103
Opened 2022-07-05 20:42 UTC by wucherpfennig

## Description
Add accordion component. see #99 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

2022-07-06 20:31 UTC, wucherpfennig commented
I did not expect this to happen... ;-) 

I assume this is because of the added lock files from the last commit. 
I think it is up to you to either "fix" the lock file or you decide to continue with php > 7.4 @kevinpapst 

same goes for the other PR I suggested #104

2022-07-06 22:37 UTC, kevinpapst commented
Nah. My mistake. I committed composer.lock which was created with PHP 8.1 - I'll check that tomorrow

2022-07-07 13:05 UTC, kevinpapst commented
Sorry for that, can you please merge master into your branches

2022-07-07 18:41 UTC, wucherpfennig commented
Done

2022-08-05 10:28 UTC, kevinpapst commented
And one last sorry for forgetting to come back to this PR.
What about a short docs page and I will add it then to the example app?

2022-08-23 11:43 UTC, wucherpfennig commented
Sorry for the long delay. I have added the required docs.

2022-08-23 12:39 UTC, wucherpfennig commented
Updated docs for this PR too.

2022-08-23 13:08 UTC, cavasinf commented
I was about to do it, need that component 👍

2022-08-23 20:20 UTC, kevinpapst requested changes

2022-08-23 20:20 UTC, kevinpapst commented on docs/components-accordion.md
> +|   items   | Array of [Item](#Step)     |  `array`  |  `[]`   |
```suggestion
|   items   | Array of [Item](#Item)     |  `array`  |  `[]`   |
```

2022-08-23 20:20 UTC, kevinpapst commented on docs/components-accordion.md
> +    } %}
The docs above say array of objects, here we have an object of objects. Lets change that, if the key is not required
```suggestion
{% set items = [
        {
          'title': 'Title 1',
          'body': 'Body 1',
        },
        {
          'title': 'Title 1',
          'body': 'Body 2',
          'options':
          {
            'title_extraClass': 'bg-success text-white',
            'body_extraClass': 'bg-danger pt-3',
          },
        },
        {
          'title': 'Title 3',
          'body': 'Body 3',
          'options':
          {
            'extraClass': 'bg-danger-lt'
          }
        },
        {
          'title': '<div>Title 4 <strong>with HTML</strong></div>',
          'body': '<div>Body 4 <strong>with HTML</strong></div',
        },
    ] %}
```

2022-08-23 20:20 UTC, kevinpapst commented on templates/components/accordion.html.twig
> +            <div class="accordion-item {{ _item_extraClass }}">
Why are those called `xxx_extraClass`? Wouldn't be `xxx_class` sufficient?

2022-08-23 20:23 UTC, kevinpapst commented
@cavasinf the best review is using the component, could you give it a try already?

2022-08-24 07:56 UTC, cavasinf reviewed
Tweaking+ Reformatting the doc

2022-08-24 07:56 UTC, cavasinf commented on templates/components/accordion.html.twig
> +    {% set _always_open = options.always_open ?? false %}
As we said before @kevinpapst, we should keep the code to `CamelCase` only.
`always_open` ➡️ `alwaysOpen `

User macro's options should always be like that, but OUR code can be like `title_class` or `titleClass` ?

2022-08-24 07:56 UTC, cavasinf commented on templates/components/accordion.html.twig
> +                        {% if _raw == true %}{{ item.title | raw }}{% else %}{{ item.title }}{% endif %}
```suggestion
                        {% if _raw %}{{ item.title | raw }}{% else %}{{ item.title }}{% endif %}
```

2022-08-24 07:56 UTC, cavasinf commented on templates/components/accordion.html.twig
> +                        {% if _raw == true %}{{ item.body | raw }}{% else %}{{ item.body }}{% endif %}
```suggestion
                        {% if _raw %}{{ item.body | raw }}{% else %}{{ item.body }}{% endif %}
```

2022-08-24 07:56 UTC, cavasinf commented on templates/components/accordion.html.twig
> +                        {% if _raw == true %}{{ item.title | raw }}{% else %}{{ item.title }}{% endif %}
@wucherpfennig what's happening if there is no `title` with the item ?

2022-08-24 07:56 UTC, cavasinf commented on docs/components-accordion.md
> +{{ accordion(items, options) }}
```suggestion
### Parameters
`accordion()` macro, waits for 2 parameters:

| Parameter | Description                |   Type    | Default |
|:---------:|:---------------------------|:---------:|:-------:|
|   items   | Array of [Item](#Item)     |  `array`  |  `[]`   |
|  options  | [Options](#Options) object | `object`  |  `{}`   |

#### Item
| Parameter | Description                                          |   Type   |    Default     |
|:---------:|------------------------------------------------------|:--------:|:--------------:|
|   title   | Title of the item                                    | `string` |      `#`       |
|   body    | Content of the item, can be `HTML` with `raw` option | `string` | _empty string_ |
|  options  | Customize the [Item Options](#Item Options)          | `object` |      `{}`      |

##### Item Options
|    Parameter     | Description              |   Type   |    Default     |
|:----------------:|--------------------------|:--------:|:--------------:|
| title_extraClass | Class for the item title | `string` | _empty string_ |
| body_extraClass  | Class for the item body  | `string` | _empty string_ |

#### Options
|  Parameter  | Description                              |   Type    |             Default             |
|:-----------:|------------------------------------------|:---------:|:-------------------------------:|
|     id      | Set custom `id` to accordion             | `string`  | `'accordion-'` + `rand(0, 999)` |                                        
|     raw     | Use raw output for `title` and `body`    | `boolean` |             `true`              |                                        
|    flush    | Remove padding. See tabler.              | `boolean` |             `false`             | 
| always_open | Do not close previous items on click.    | `boolean` |             `false`             |   
| extraClass  | Add extra classes on accordion container | `string`  |         _empty string_          |      

### Usage

```twig
{% from '@Tabler/components/accordion.html.twig' import accordion %}

{% set items = [
    {
        'title': 'Title 1',
        'body': 'Body 1',
    },
    {
        'title': 'Title 2',
        'body': 'Body 2',
        'options':
        {
            'title_extraClass': 'bg-success text-white',
            'body_extraClass': 'bg-danger pt-3',
        },
    },
    {
        'title': 'Title 3',
        'body': 'Body 3',
        'options':
        {
            'extraClass': 'bg-danger-lt'
        }
    },
    {
        'title': '<div>Title 4 <strong>with HTML</strong></div>',
        'body': '<div>Body 4 <strong>with HTML</strong></div',
    },
] %}

{% set options = {
    'id': 'example-accordion',
    'raw': true,
    'always_open': false,
    'extraClass': 'mb-0',
} %}

{{ accordion(items, options) }}
```

2022-08-24 07:56 UTC, cavasinf commented on docs/components-accordion.md
> +{{ accordion(items, options) }}
I'm not OK with `flush` option description.
There's no information about that in Tabler, but can be found with Bootstrap https://getbootstrap.com/docs/5.0/components/accordion/#flush

2022-08-24 07:56 UTC, cavasinf commented on templates/components/accordion.html.twig
> +                    <button class="accordion-button {% if loop.first == false %}collapsed{% endif %}"
`is item open` should be an item option, not if not first loop.

Example, I want to have the second accordion item to be opened when arriving in the page.

2022-08-24 08:00 UTC, cavasinf commented
@kevinpapst I'm in holidays RN, only thing I can do is "check by eye" and test it next Monday.

2022-09-01 10:36 UTC, cavasinf commented
I've already suggested a DOC update, but it is outdated now 😢 
But it was almost like yours now 👍

2022-09-01 10:38 UTC, kevinpapst commented
I've seen that (thanks 😄 ) - but it was impossible to read, as it was so long and Github rendered it awfully, no chance to understand changes.

2022-09-01 11:11 UTC, wucherpfennig commented
Hey guys what do I need to do to help you? (Writing better code in the first place is not an option 😉)

2022-09-01 11:13 UTC, kevinpapst commented
@wucherpfennig you could update to use my latest changes and then check the comments by @cavasinf 

I haven't done a demo implementation yet, will do and provide feedback as well asap.

2022-09-01 21:53 UTC, wucherpfennig reviewed
looks good

2022-09-01 21:54 UTC, wucherpfennig commented
Oh come on... tbh I do not know what else I should do ;-)

2022-09-07 14:55 UTC, cavasinf commented on docs/components-accordion.md
> +|    flush    | Remove padding (see Tabler docs)         | `boolean` |    `false`     |
I'm not OK with flush option description.
There's no information about that in Tabler, but can be found with Bootstrap https://getbootstrap.com/docs/5.0/components/accordion/#flush

2022-09-08 06:42 UTC, cavasinf commented
LGTM now 👍

2022-09-08 09:57 UTC, kevinpapst approved these changes
I'll merge, add a demo page and check if everything works as expected.
Thanks @wucherpfennig 😄

2022-09-08 09:58 UTC, merged