[Feature] Add error layout + layout fullpage
kevinpapst/TablerBundle pull request #46
Opened 2022-01-03 15:55 UTC by cavasinf

## Description
Add `error` layout page.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

2022-01-07 23:34 UTC, kevinpapst commented
Thank you @cavasinf - works great!

I did some smaller refactorings and added [examples to the demo app](https://github.com/kevinpapst/TablerBundle-Demo/pull/5). It now uses the `status_code`  and `status_text` as fallback for missing translations:
<img width="382" alt="Bildschirmfoto 2022-01-08 um 00 26 56" src="https://user-images.githubusercontent.com/533162/148619957-fbe8f84c-2a27-4d02-9b3c-e76d0b964cc8.png">

Can you adjust the French translation? It currently sounds as if it is targeted for 404 "page not found", but I think we should provide a generic error message instead. After that I will merge.

2022-01-08 09:42 UTC, kevinpapst requested changes
Please check French translation, I changed English and German yesterday. Everything els eis good to go from my side. But probably you wanna try my changes first?

2022-01-08 09:50 UTC, cavasinf commented
Looks Good, but I'm not at my workspace rn.
Can only check next Monday.

2022-01-08 09:57 UTC, cavasinf commented on translations/TablerBundle.fr.xliff
> +                <target>Nous sommes désolé, mais la page que vous cherchez n'a pas été trouvée</target>
```suggestion
                <target>Nous sommes désolés mais quelque chose s'est mal passé</target>
```

2022-01-08 10:14 UTC, kevinpapst commented
Oh right: it is weekend, totally forgot 😁 thanks for contributing during your free time!

2022-01-08 10:15 UTC, kevinpapst approved these changes
Waiting with merge for your final tests!

2022-01-10 09:04 UTC, cavasinf commented
@kevinpapst The "Take me home" trans doesn't work.
But I can't find why ...

![image](https://user-images.githubusercontent.com/25293190/148740764-41032369-b096-4a65-b3c0-b64fefa12d93.png)

2022-01-10 09:56 UTC, kevinpapst commented
Just tested, works for me: 

<img width="358" alt="Bildschirmfoto 2022-01-10 um 10 55 54" src="https://user-images.githubusercontent.com/533162/148747014-f623cc57-e7fc-407c-a2ad-d9f884c61c36.png">
 
<img width="414" alt="Bildschirmfoto 2022-01-10 um 10 56 14" src="https://user-images.githubusercontent.com/533162/148747062-bba25672-84e3-4ba3-a9b8-a52d98fef740.png">

Cache?

2022-01-10 10:05 UTC, cavasinf commented
`php bin/console cache:clear` and `rm var/ -R` didn't change anything..

2022-01-10 10:09 UTC, kevinpapst commented
I am testing in APP_ENV=prod and just did `rm -rf var/cache/*` after updating the branch.
Lets merge and see what happens then.

2022-01-10 10:09 UTC, merged