Refactoring `alert()` macro
kevinpapst/TablerBundle pull request #90
Opened 2022-05-31 12:59 UTC by cavasinf

## Description
Related to #89 

#### Usage

```twig
{% from '@Tabler/components/alert.html.twig' import alert %}

<div class="row">
    <div class="col-6">
        {{ alert('danger', 'Description' ,'Title', 'fas fa-exclamation-triangle', true) }}
        {{ alert('danger', 'Description' ,'Title', 'fas fa-exclamation-triangle') }}
        {{ alert('warning', 'Description' ,'Title') }}
        {{ alert('warning', null ,'Title') }}
        {{ alert('warning', null ,'Title', 'fas fa-exclamation-triangle') }}
        {{ alert('success', 'Description') }}
        {{ alert('success', 'Description', null, 'fas fa-exclamation-triangle') }}
        {{ alert('primary') }}
    </div>

    <div class="col-6">
        {{ alert({title : 'Title V2', description: 'Descrition V2', icon : 'warning', dismissible : true}) }}
        {{ alert({title : 'Title V2', description: 'Descrition V2', icon : 'warning'}) }}
        {{ alert({title : 'Title V2', description: 'Descrition V2', type : 'warning'}) }}
        {{ alert({title : 'Title V2', type : 'warning'}) }}
        {{ alert({title : 'Title V2', icon : 'warning', type : 'warning'}) }}
        {{ alert({description : 'Description V2', type : 'success'}) }}
        {{ alert({description : 'Description V2', type : 'success', icon : 'warning'}) }}
        {{ alert({type : 'primary'}) }}
    </div>
</div>
```

#### Preview

![image](https://user-images.githubusercontent.com/25293190/171178960-86d34f35-7d38-416f-8d52-405cc5a5f4b5.png)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

2022-05-31 14:05 UTC, kevinpapst requested changes
Can you make the raw filter optional by a setting like in my example.
This filter can easily lead to CSRF issues if you pass user generated values to it. 
Better activate it per case, instead of "blindly" using unescaped data.

2022-05-31 14:05 UTC, kevinpapst commented on templates/components/alert.html.twig
> +
{% set _raw = (options.raw ?? false) is same as (true) %}

2022-05-31 14:05 UTC, kevinpapst commented on templates/components/alert.html.twig
> +                        <h3 class="{{ _description is not empty ? 'mb-1' : 'mb-0' }}">{{ _title|raw }}</h3>
{% if _raw %}{{ _title|raw }}{% else %}{{ _title }}{% endif %}

2022-05-31 16:55 UTC, cavasinf commented
Everything's OK for me 👌

Le mar. 31 mai 2022, 18:05, Kevin Papst ***@***.***> a écrit :

> nice 👍 ready for merge from your end?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kevinpapst/TablerBundle/pull/90#issuecomment-1142327304>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGA7DBXOD3GBTBJAVPLJQI3VMY2DTANCNFSM5XNPTRPQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-01 07:07 UTC, merged

2022-06-01 07:08 UTC, kevinpapst commented
I will add your examples to the demo application. Thanks you @cavasinf 👍

2022-06-01 07:20 UTC, cavasinf commented
Yeah I haven't seen a doc for that kind of feature.
We can maybe add the doc of that component is this repo like others 🤔

2022-06-01 07:39 UTC, kevinpapst commented
This is what I see after the merge:
<img width="1339" alt="Bildschirmfoto 2022-06-01 um 09 38 27" src="https://user-images.githubusercontent.com/533162/171352643-64a65afc-ec18-4e46-8054-9b8b55d95c70.png">
Can you confirm that is still looks as in your screenshot?

2022-06-01 07:42 UTC, kevinpapst commented
> Yeah I haven't seen a doc for that kind of feature.

Because you still don't use the demo app, do you 😁

2022-06-01 07:52 UTC, kevinpapst commented
Okay, there is one BC break which is not matching the Tabler docs: https://preview.tabler.io/docs/alerts.html

Before:
<img width="235" alt="Bildschirmfoto 2022-06-01 um 09 45 33" src="https://user-images.githubusercontent.com/533162/171354912-214005d9-4aa4-42e3-b619-198373033998.png">
 
After:
<img width="253" alt="Bildschirmfoto 2022-06-01 um 09 51 29" src="https://user-images.githubusercontent.com/533162/171354959-2cbac33a-28cd-4fa5-a0ff-a0d99060a88c.png">

Could you have a look while I work on the docs?

2022-06-03 07:10 UTC, cavasinf commented
@kevinpapst Looks like it's coming from the `icon` class again.

Tabler user SVG, we use FontAwesome.
Can you try with `false` param at `tabler_icon` twig function.
https://github.com/kevinpapst/TablerBundle/blob/da494e86cab2d04f5ea500ab04850cb918d8a675/templates/components/alert.html.twig#L34

I remember it was "odd" without this class, but if it's okay for you, we can switch that 👍

2022-06-03 07:15 UTC, cavasinf commented
I'll check for title color + description => new PR ?

2022-06-03 07:29 UTC, kevinpapst commented
I don't mind the icon size/positioning, bigger looks better and I didn't even recognize it before you mentioned it ;-)

I was only talking about the colors, which worked before. New PR sounds good :)

2022-06-07 06:59 UTC, kevinpapst commented
Going through my deprecations log, I saw that we missed one: 
https://github.com/kevinpapst/TablerBundle/blob/main/templates/components/callout.html.twig#L3

`callout` is calling `alert` with single params 🙄

2022-06-07 07:35 UTC, cavasinf commented
What do you want to do ? 
Add the deprecated message and change multi params into object one param

2022-06-07 08:11 UTC, kevinpapst commented
Because important is the 6 param and it got lost somewhere in the refactoring process.
So have a consistent API we should change the signature as well:
```
{% from '@theme/components/alert.html.twig' import alert %}
{% if type is iterable %}
    {{ alert(type) }}
{% else %}
    {% deprecated "Passing multiple parameters to 'callout()' Tabler macro is deprecated, use options object syntax." %}
    {{ alert({type: type|default('danger'), description: description, title: title|trans, icon: icon, dismissible: false, important: true}) }}
{% else %}
```

What do you think ?

2022-06-07 08:32 UTC, cavasinf commented
Missing the trans of `description` (like OLD alert macro) but LGTM 👍

2022-06-07 08:37 UTC, cavasinf commented
- Missing the trans of `description` (like OLD alert macro)
- `icon` is required in callout macro ?
- `description` is required ?
- Maybe add `{% set options = type %}` inside if condition (if devs looks at code).